services:
  - type: web
    name: eastaccess-alpr
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: RUN_HARDWARE
        value: "0"
